Add users table and authentication and authorization
abdullahshahzad7890/DotnetUpSkill pull request #2
Opened 2023-12-28 12:06 UTC by abdullahshahzad7890

2024-01-02 10:03 UTC, ArbazCh commented on TodoApp/Controllers/AuthController.cs
> +            if (_userRepository.UserExists(request.Username))
use async/await for repository operations.

2024-01-02 10:08 UTC, ArbazCh commented on TodoApp/Controllers/AuthController.cs
> +                claims.Add(new Claim(ClaimTypes.Role, "Admin"));
Make an enum for Roles instead of using like "Admin"

2024-01-02 10:14 UTC, ArbazCh commented on TodoApp/Controllers/TodoAppController.cs
> +            if (!User.IsInRole("Admin") && todoToUpdate.CreatedByUserId != User.FindFirst(ClaimTypes.NameIdentifier)?.Value)
refactor the condition. it is not readable.

2024-01-02 10:15 UTC, ArbazCh commented on TodoApp/Data/DataContext.cs
>          protected override void OnModelCreating(ModelBuilder modelBuilder)
why we need model builder here?

2024-01-02 10:21 UTC, ArbazCh commented on TodoApp/Controllers/AuthController.cs
> +        private bool verifyPasswordHash(string password, byte[] passwordHash, byte[] passwordSalt)
Methods name should be in Pascal.

2024-01-02 10:28 UTC, ArbazCh commented on TodoApp/Controllers/TodoAppController.cs
> -                return StatusCode(402, ModelState);
why  status code 402 here?

2024-01-02 10:39 UTC, ArbazCh commented on TodoApp/Controllers/TodoAppController.cs
> +
remove extra line.

2024-01-02 10:42 UTC, ArbazCh commented on TodoApp/Controllers/TodoAppController.cs
> +
remove extra line from here as well remove from other places if needed.

2024-01-02 10:44 UTC, ArbazCh commented on TodoApp/Controllers/TodoAppController.cs
Cannot we make one condition for return of "Bad Request"?

2024-01-02 10:45 UTC, ArbazCh commented on TodoApp/Controllers/TodoAppController.cs
> +
remove extra line.

2024-01-02 10:45 UTC, ArbazCh commented on TodoApp/Data/DataContext.cs
remove extra line.

2024-01-02 10:48 UTC, ArbazCh requested changes
please resolve comments. thank you.

2024-01-04 09:47 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/AuthController.cs
> +                claims.Add(new Claim(ClaimTypes.Role, "Admin"));
Done as suggested. Thank you!

2024-01-04 09:47 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/TodoAppController.cs
> +            if (!User.IsInRole("Admin") && todoToUpdate.CreatedByUserId != User.FindFirst(ClaimTypes.NameIdentifier)?.Value)
Done as suggested. Thank you!

2024-01-04 09:47 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/AuthController.cs
> +        private bool verifyPasswordHash(string password, byte[] passwordHash, byte[] passwordSalt)
Done as suggested. Thank you!

2024-01-04 09:49 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/TodoAppController.cs
> -                return StatusCode(402, ModelState);
Updated to BadRequest

2024-01-04 09:49 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/TodoAppController.cs
> +
Done. Thank you!

2024-01-04 09:49 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/TodoAppController.cs
> +
Done. Thank you!

2024-01-04 09:53 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/TodoAppController.cs
Done. Thank you!

2024-01-04 09:53 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/TodoAppController.cs
> +
Done. Thank you!

2024-01-04 09:54 UTC, abdullahshahzad7890 commented on TodoApp/Data/DataContext.cs
Done. Thank you!

2024-01-04 10:09 UTC, abdullahshahzad7890 commented on TodoApp/Controllers/AuthController.cs
> +            if (_userRepository.UserExists(request.Username))
Done as suggested. Thank you!

2024-01-04 10:24 UTC, abdullahshahzad7890 commented on TodoApp/Data/DataContext.cs
>          protected override void OnModelCreating(ModelBuilder modelBuilder)
ModelBuilder is used here to seed initial data into the database when it's created.

2024-01-04 12:42 UTC, ArbazCh approved these changes
Suggestions: 
- Please try to format the code (ctrl K+D) and remove extra lines. 
- Still at some places there need to refactor the conditions. 
- Try to use asynchronous programming where needed.

2024-01-05 10:03 UTC, merged